### ISSUE TITLE
ArgumentError: Error #3500: The extension context does not have a method with the name isSupported.

### ISSUE THREAD

**Issue by gaodeng** [tuarua/LibHelloWorldANE64-master#1]
Tried LibHelloWorldANE64-master-master/LibHelloWorldANE64Example/bin-release/LibHelloWorldANE64Example.app   still get Error#3500

**Comment by tuarua** [comment]
Have you tried building the sample Flash Builder project yourself?
It may be that github has scrambled the .app file
